name: .NET Core

on:
  push:
    branches: [ VS-2022 ]
  pull_request:
    branches: [ VS-2022 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build --no-restore --configuration Release
    - name: Test with dotnet
      run: dotnet test ./Clean.Architecture.sln --no-build --configuration Release
