name: publish Ardalis.CleanArchitecture Template to nuget
on:
  push:
    branches:
      - VS-2022 # Your default release branch
    paths:
      - 'CleanArchitecture.nuspec'
jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'
          
      - name: Package the template
        run: nuget pack CleanArchitecture.nuspec -NoDefaultExcludes
        
      - name: Publish to nuget.org
        run: nuget push Ardalis.CleanArchitecture.Template.*.nupkg -src https://api.nuget.org/v3/index.json ${{secrets.NUGET_API_KEY}}
